### ISSUE TITLE
Reduce heavy dependencies

### ISSUE THREAD

**Issue by fabiospampinato** [dagrejs/graphlib#103]
I see the entirety of `lodash` is being imported, while only a handful of its methods are being used.

Importing only the required methods would be beneficial to bundle size.

**Comment by crushjz** [comment]
I agree with that! I think it is crucial if the library is used in a front-end app.

**Comment by zmitry** [comment]
https://github.com/zmitry/graphlib
Check this out, it doesn't have this issue.

**Comment by darscan** [comment]
A PR exists to address this: https://github.com/dagrejs/graphlib/pull/118

**Comment by rustedgrail** [comment]
Lodash is no longer a dependency for graphlib. As I get to it, I'm removing it from the rest of the libraries.
