### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by samestep** [dagrejs/graphlib#146]
Hello! Thanks so much for making and maintaining this library, it's quite useful.

We (@penrose) were wondering when the next npm release of graphlib will be; presumably 2.1.9?

https://github.com/dagrejs/graphlib/blob/e864ad6ba2619ad9f40984c9d938ed2e7eec9b63/package.json#L3

Specifically, graphlib 2.1.8 is blocking us from switching our build system to Vite. The latest commit in the graphlib repo works just fine for us with Vite, but we can't just use a GitHub dependency in `package.json` because that doesn't include the `compiled/` directory. See this discussion: https://github.com/penrose/penrose/pull/964#issuecomment-1125471225

**Comment by samestep** [comment]
@rustedgrail I was super excited to see commit c464a1c9e60766aa93b491ee584e9a72768ba3d7! Could you upload that release to npm?

**Comment by rustedgrail** [comment]
I'm slowly working on this. I need to get the NPM permissions corrected before I can release.

**Comment by samestep** [comment]
Ah OK, makes sense; thanks! Sorry for rushing you.

**Comment by Jona898** [comment]
You can also install a git repo as npm dependency.
https://docs.npmjs.com/cli/v8/commands/npm-install

For Example: npm i -S git://git@github.com/dagrejs/graphlib#v3.0.1 or npm i -S git://git@github.com/dagrejs/graphlib#eb6f40fa7281169f412831925275f51700ba7c57

**Comment by samestep** [comment]
@Jona898 Right, we tried that and unfortunately it doesn't work; as I mentioned in my comment above:

> we can't just use a GitHub dependency in `package.json` because that doesn't include the `compiled/` directory
