### ISSUE TITLE
Recursive DFS implementations

### ISSUE THREAD

**Issue by ethan-keller** [dagrejs/graphlib#147]
Hi dagrejs team,

Like mentioned in this issue: dagrejs/dagre#327 I ran into some problems when using **dagre** on bigger graphs. Since **dagre** uses **graphlib** internally, some of the errors originated from **graphlib**. 
In `lib\alg\dfs.ts`, the DFS function is implemented **recursively** which resulted in `max call stack size` errors when using it with big graphs (3000+ nodes).

It would be a good idea to **rewrite** the recursive DFS functions to iterative DFS functions to avoid `max call stack size` errors.

**Comment by rustedgrail** [comment]
Implemented in https://github.com/dagrejs/graphlib/pull/174, which is a reimplementation of https://github.com/dagrejs/graphlib/pull/148.
