### ISSUE TITLE
Who owns this and is it really being maintained?

### ISSUE THREAD

**Issue by 0xalecks** [dagrejs/graphlib#159]
The readme states this project is being maintained again, but there hasn't been any activity in 3 months, and there's tons of PRs waiting. 

This comment here implies there's confusion about who owns this and what can be done:
https://github.com/dagrejs/graphlib/pull/98#issuecomment-615853298

So... what's the state of this library? and are there any good alternatives? I saw this one mentioned a few times, but it also looks like it hasn't seen an update in 3 years
https://github.com/zmitry/graphlib

**Comment by lutzroeder** [comment]
@rustedgrail

**Comment by rustedgrail** [comment]
Hello Oxalecks,

I am working on upgrading this and the other dagrejs projects and then I will look into the pull requests. In December, I'll have more time and should be able to release a working version. After that, I will look through the pull requests & issues, see what's still relevant and merge, update or close them.

**Comment by rustedgrail** [comment]
I'm going through the PRs and Issues and closing or merging what I can.
