### ISSUE TITLE
Replacing Dagre with Graphlib

### ISSUE THREAD

**Issue by 32teeth** [dagrejs/graphlib#161]
In Dagre, we had `layout`
How do i implement the auto layout now?

**Comment by rustedgrail** [comment]
Dagre still has layout and you should still use that.

I'm working on making sure that Dagre is also updated and working with the updated Graphlib. I'll get new versions of Graphlib and Dagre in NPM as I get time to work on them.

**Comment by 32teeth** [comment]
Thanks @rustedgrail
