### ISSUE TITLE
Unexpected character '#'

### ISSUE THREAD

**Issue by dagadbm** [dagrejs/graphlib#192]
I am using node 16 ( I cannot update to node 17 as there are a ton of dependencies that would break my project.

I am getting this error on the front-end:

```
/node_modules/@dagrejs/graphlib/lib/graph.js 18:2
Module parse failed: Unexpected character '#' (18:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class Graph {
>   #isDirected = true;
|   #isMultigraph = false;
|   #isCompound = false;
```

```
./node_modules/@dagrejs/graphlib/lib/data/priority-queue.js 9:2
Module parse failed: Unexpected character '#' (9:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| class PriorityQueue {
>   #arr = [];
|   #keyIndices = {};
```

Is there a way to make graphlib still support node 16?

I really wanted to try to use the latest version of dagre because of the whole ordering logic.

It is very weird when I add new nodes to the graph the graph always gets redirected in a completely random way (still unsure how to fix this in dagre but hoping I can get some support on this as well)

**Comment by rustedgrail** [comment]
Merged a PR to replace # with _

https://github.com/dagrejs/graphlib/pull/194
