### ISSUE TITLE
graph.js will crash if there's a node named `hasOwnProperty`

### ISSUE THREAD

**Issue by ddadamhooper** [dagrejs/graphlib#200]
The bug is pretty clear: a node named `hasOwnProperty` will make the `this._nodes.hasOwnProperty(...)` calls fail.

https://github.com/dagrejs/graphlib/blob/19cd7c02f8ccbf6a88b206cc867ea672c4931810/lib/graph.js#L195

As seen in this little big of JS trivia:

```javascript
const _nodes = { hasOwnProperty: "hi" };
_nodes.hasOwnProperty("anything"); // Uncaught TypeError: _nodes.hasOwnProperty is not a function
```

Fix: should be `Object.hasOwn(this._nodes, ...)`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#problematic_cases_for_hasownproperty

**Comment by rustedgrail** [comment]
Fixing this here and in Dagre

https://github.com/dagrejs/graphlib/pull/202
