### ISSUE TITLE
lodash 4.x support

### ISSUE THREAD

**Issue by cstolli** [dagrejs/graphlib#58]
would be nice to have this not be dependent on lodash's old `_.filter` method.  `_.filter` no longer accepts a `this` argument as it's third parameter.  In projects requiring lodash 4.x, this breaks graphlib.

I've forked and run the unit tests with `=>` fat arrow functions as the iterator for the `_.filter` calls, where I removed the `this` arguments, and it works swimmingly, but we would need to introduce babel/es6 and the associated tooling required to support that.

thoughts?

**Comment by cpettitt** [comment]
Interesting. You could also solve this using `bind` which would not require integrating ES6 support.

**Comment by cstolli** [comment]
looks like this has been solved using `bind` (smart move) per https://github.com/cpettitt/graphlib/pull/59, a release of that would be most useful :)

**Comment by AnimaLupi** [comment]
+1 for the release of the updated version with files in dist/ also updated please...
I use bower and no matter which version I fetch (latest or master) I'm getting 2.1.0.
Thanks!

**Comment by cpettitt** [comment]
Available since v2.1.1.
