### ISSUE TITLE
Merging two graphs

### ISSUE THREAD

**Issue by mlajtos** [dagrejs/graphlib#64]
Hello :)

Would it be possible to merge two graphs by combining the internal representations of them? What I have in mind is using [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) for _nodes, _parent, etc. effectively merging two graphs in O(1). Or is there any other way to do it?

Thank you for your work on Graphlib, Dagre and Dagre-D3. :)

**Comment by mathieugerard** [comment]
Hi @mlajtos,
Did you find a nice way to merging 2 graphs? I'm looking for the same thing.
Thanks
Mathieu

**Comment by mlajtos** [comment]
Hi @mathieugerard ,
I decided not to fiddle with the internal representations of graphlib. Instead I serialized them, joined the serialized representations and then deserialize:

```javascript
const g1 = new graphlib.Graph()
const g2 = new graphlib.Graph()

g1.setNode("a1")
g1.setNode("b1")
g1.setEdge("a1", "b1")
g1.setEdge("b1", "shared")

g2.setNode("a2")
g2.setNode("b2")
g2.setEdge("a2", "b2")
g2.setEdge("b2", "shared")

const g1_ser = graphlib.json.write(g1)
const g2_ser = graphlib.json.write(g2)

const g3_ser = {
  options: g1_ser.options,
  nodes: [...g1_ser.nodes, ...g2_ser.nodes],
  edges: [...g1_ser.edges, ...g2_ser.edges]
}

const g3 = graphlib.json.read(g3_ser)
console.log(g3.nodes(), g3.edges())
```

**Comment by mathieugerard** [comment]
Thank you very much. It works indeed perfectly fine.
I had looked at the json read and write methods and your answer confirms this is the way to go.
