### ISSUE TITLE
g.nodes() contains edges

### ISSUE THREAD

**Issue by sarora2073** [dagrejs/graphlib#81]
Hi,

Am trying the latest version and noticed that whenever I add an edge it modifies the node object as well..which is unexpected. 

e.g.

if i add nodes called '1', '2', then add an edge ['1','2'] then call g.nodes(), instead of returning just ['1','2'], it returns ['1','2', **'1,2'**]

Looking further into the graphcore.lib.js I suspect the culprit starts on line 996 of the setEdge prototype..copied below.

```
  // It didn't exist, so we need to create it.
  // First ensure the nodes exist.
  this.setNode(v);
  this.setNode(w);
```

From the comments in the code, it appears it was intended to do some validation on nodes before adding edges, but effectively modifies the nodes themselves, inadvertently. Please advise if i'm missing something...or if if it's a legit bug.

Thanks,

-S. Arora

**Comment by lutzroeder** [comment]
How are you calling `setEdge`?

```
<script type='text/javascript' src='https://dagrejs.github.io/project/graphlib/latest/graphlib.js'></script>
<script type='text/javascript'>
var g = new graphlib.Graph()
g.setNode('1');
g.setNode('2');
console.log(g.nodes());
g.setEdge('1', '2');
console.log(g.nodes());
</script>
```

**Comment by sarora2073** [comment]
I found out the problem. As I add each node, I add each of its associated edges, even if the target nodes don’t exist. Given the implementation above, that makes setEdge think there is a problem with missing nodes and it too creates them. I understand I can easily work around this by creating all nodes first. Nevertheless I would suggest that the code snippet above be revamped e.g. perhaps have it fail to create the edge rather adding a node per se, as it risks inadvertently creating nodes with bad data like in the example I gave.

**Comment by sarora2073** [comment]
btw, just to be clear, even if you don't want to improve the code, as it stands I would say this code is buggy..the operation to add an `edge `to a node that doesn't exist should not result in creating bad `node` data. Would suggest that this remain open.
